version: "3"

services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
    web:
        build: .
        command:
            python ./config/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/django
        ports:
            - 8000:8000
        depends_on:
            - db